version: "3.8"

services:
  identity:
    build:
      context: "Identity"
      dockerfile: Dockerfile
    image: nodesolution-identity
    ports:
    - "5000:5000"
  user:
    build:
      context: "User"
      dockerfile: Dockerfile
    image: nodesolution-user
    ports:
    - "5001:5001"
  nginx:
    build:
      context: "Nginx"
      dockerfile: Dockerfile
    image: nodesolution-nginx
    ports:
    - "3001:80"
