module.exports = {
  SECRET_KEYS: {
    IDENTITY_SERVICE_URL        : 'IdentityServiceURL',
    AUDIT_LOG_SERVICE_URL       : 'AuditLogServiceURL',
    META_DATA_SERVICE_URL       : 'MetaDataServiceURL',
    NOTIFICATION_SERVICE_URL    : 'NotificationServiceURL',
    USER_MANAGEMENT_SERVICE_URL : 'UserManagementServiceURL',

    FAST_API_URL      : 'FastAPIURL',
    FAST_API_USERNAME : 'FastAPIUserName',
    FAST_API_PASSWORD : 'FastAPIPassword',
    MAIN_API          : 'MainAPI',

    AWS_SBUCKET_NAME    : 'AWSSbucketName',
    AWS_REGION          : 'AWSRegion',
    AWS_MAIN_CONTAINER  : 'AWSMainContainer',
    AWS_MDG_CONTAINER   : 'AWSMDG_Container',
    AWS_S3IMPORT_BUCKET : 'AWSS3ImportBucket',

    EMAIL_HOST          : 'Emailhost',
    EMAIL_PORT          : 'Emailport',
    EMAIL_ENABLE_SSL    : 'EmailenableSsl',
    EMAIL_PASSWORD      : 'Emailpassword',
    SENDGRID_FROM_EMAIL : 'SendGridFromEmail',
    SENDGRID_FROM_NAME  : 'SendGridFromName',
    SENDGRID_API_KEY    : 'SendGridAPIKey',

    JWT_DMS_KEY                          : 'JWTDMSkey',
    JWT_EXTERNAL_SERVICE_KEY             : 'JWTExternalServiceKey',
    JWT_TOKEN_EXPIRE_TIME_IN_MIN         : 'JWTTokenExpireTimeInMin',
    SECRET_KEY                           : 'SecretKey',
    CLIENT_APP_URL                       : 'clientappurl',
    RESET_PASSWORD_URL                   : 'ResetPasswordURL',
    JWT_REFRESH_TOKEN_EXPIRE_TIME_IN_MIN : 'JWTRefreshTokenExpireTimeInMin',
    ENCRYPTION_KEY                       : 'EncyptionKey',
    USER_ACTIVATION_URL                  : 'UserActivationURL',

    LIVE_RAMP_PULSEPOINT_SFTP  : 'LiveRampPulsepointSFTP',
    LIVE_RAMP_ADTHEORENT_SFTP  : 'LiveRampAdtheorentSFTP',
    LIVE_RAMP_VIANT_SFTP       : 'LiveRampViantSFTP',
    LIVE_RAMP_VIDEOAMP_SFTP    : 'LiveRampVideoampSFTP',
    LIVE_RAMP_AMOBEE_SFTP      : 'LiveRampAmobeeSFTP',
    LIVE_RAMP_DEV_SFTP         : 'LiveRampDevSFTP',
    LIVE_RAMP_VALASIS_SFTP     : 'LiveRampValasisSFTP',
    LIVE_RAMP_VDX_SFTP         : 'LiveRampVdxSFTP',
    LIVE_RAMP_STACK_ADAPT_SFTP : 'LiveRampStackAdaptSFTP',
    LIVE_RAMP_SFTP_SERVER      : 'LiveRampSFTPServer',
    LIVE_RAMP_SFTP_USERNAME    : 'LiveRampSFTPUserName',
    LIVE_RAMP_SFTP_PASSWORD    : 'LiveRampSFTPPassword',
    LIVE_RAMP_PORT             : 'LiveRampPort',
    LIVE_RAMP_EXCEPTION_MAIL   : 'LiveRampExceptionMail',
    LIVE_RAMP_DEV_AHCP_SFTP    : 'LiverampDevAhcpSFTP',

    COHORT_OUTPUT_FILEPATH  : 'CohortOutputFilePath',
    COHORT_SUMMARY_FILEPATH : 'CohortSummaryFilePath',
    COHORT_ERROR_FILEPATH   : 'CohortErrorFilePath',
    COHORT_INPUT_FILEPATH   : 'CohortInputFilePath',

    AWS_COHORT_BUCKET_NAME : 'AWSCohortBucketName',
    AWS_COHORT_ACCESS_KEY  : 'AWSCohortAccessKey',
    AWS_COHORT_SECRET_KEY  : 'AWSCohortSecretKey',

    PRODUCTION_ENVIORNMENT : 'ProductionEnviornment',
    LOOKUP_PATH            : 'LookupPath',
    MAIN_CONTAINER         : 'MainContainer',
    AWS_BUCKET_NAME        : 'AWSBucketName',
    AWS_PROFILE_NAME       : 'AWSProfileName',
    AWS_ACCESS_KEY         : 'AWSAccessKey',
    AWS_SECRET_KEY         : 'AWSSecretKey',

    SLACK_ERROR_EMAIL_ID : 'SlackErrorEmailId',
    TO_ADMIN_EMAIL       : 'ToAdminEmail',
    SF_USERNAME          : 'SFUserName',
    SF_PASSWORD          : 'SFPassword',
    SF_CLIENT_ID         : 'SFClientId',
    SF_CLIENT_SECRET     : 'SFClientSecret',
    SF_SECRET_KEY        : 'SFSecretKey',
    PLD_LIVE_RAMP_BUCKET : 'PLDLiveRampBucket',
    RTA_PATH             : 'RtaPath',

    CAPTCHA_SITE_KEY     : 'CaptchaSitekey',
    CAPTCHA_SECRET_KEY   : 'CaptchaSecretKey',
    CAPTCHA_BY_PASS_USER : 'CaptchaByPassUser',

    QUICK_SIGHT_ACCOUNT_ID        : 'QuickSightAccountId',
    QUICK_SIGHT_ACCESS_KEY_ID     : 'QuickSightAccessKeyId',
    QUICK_SIGHT_SECRET_ACCESS_KEY : 'QuickSightSecretAccessKey',
    QUICK_SIGHT_ROLE              : 'QuickSightRole',
    QUICK_SIGHT_ROLE_SESSION_NAME : 'QuickSightRoleSessionName',

    DATA_REQUEST_MAIL_ID : 'DataRequestMailId',
    HANG_FIRE_SERVICEURL : 'HangfireServiceURL'
  }
};
